server:
  port: 8000
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service?allowPublicKeyRetrieval=true&useSSL=false"
    username: root
    password: Kiet@123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true